name: Maven verify pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 11, 17]
    env:
      OS: ${{ matrix.os }}
      JAVA: ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build
        run: |
          mvn clean verify --no-transfer-progress
      - name: Publish coverage
        uses: codecov/codecov-action@v2
        with:
          env_vars: OS,JAVA
